name: M365 Auto Renew

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Tự động chạy mỗi 6 tiếng một lần

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install requests uvicorn fastapi  # Cài đặt thủ công các thư viện bạn đang thiếu

      - name: Run Renew Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          ACCOUNT_ID: ${{ secrets.CLIENT_ID }}
          ACCOUNT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: python main.py
